import {defaultSampler} from './d3d9-samplers.js';
import {TextureStorage} from './gpu-textures.js';
import {DrawRenderer,decodeDraw} from './d3d9-draw.js';
import {ShaderObjects} from './shader-objects.js';
import {GeometryBuffers} from './gpu-buffers.js';
import {D3D9RenderState,RS} from './d3d9-state.js';
export function diagnosticDrawPacket(vertex,pixel,vb,index=0,texture=0,textureStage=0){
 const state=new D3D9RenderState();state.set(RS.CULLMODE,1);state.set(RS.ZENABLE,0);
 const declaration=new Uint8Array([0,0,0,0,3,0,0,0,0,0,16,0,3,0,10,0,255,0,0,0,17,0,0,0]);
 const words=[0x39445246,vertex,pixel,4,3,0,index,0,2,declaration.length,20];for(let i=0;i<16;i++)words.push(i===0?vb:0,0,i===0?32:0);for(const [k,v]of Object.entries(state.values))words.push(Number(k),v);words.push(...new Uint32Array(declaration.buffer),...new Uint32Array(1312));const slots=new Uint32Array(16);slots[textureStage]=texture;words.push(...slots);for(let i=0;i<16;i++)words.push(...defaultSampler());words.push(0,0,32,32,0,0x3f800000);return new Uint8Array(new Uint32Array(words).buffer);
}
export async function testDrawPackets(device,translator,vs,ps){
 const objects=new ShaderObjects(translator),buffers=new GeometryBuffers(device),color=device.createTexture({size:[32,32],format:'bgra8unorm',usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.COPY_SRC}),depth=device.createTexture({size:[32,32],format:'depth24plus-stencil8',usage:GPUTextureUsage.RENDER_ATTACHMENT}),read=device.createBuffer({size:8192,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});
 const textures=new TextureStorage(device),renderer=new DrawRenderer(device,{shaders:objects,buffers,textures,color,depth}),memory=new SharedArrayBuffer(32768),samples=[];device.pushErrorScope('validation');
 try{
  const vertex=objects.create(0,vs),pixel=objects.create(1,ps),values=new Float32Array([-.8,-.8,.5,1,.25,.5,.75,1,.8,-.8,.5,1,.25,.5,.75,1,0,.8,.5,1,.25,.5,.75,1]);new Uint8Array(memory,4096,values.byteLength).set(new Uint8Array(values.buffer));const vb=await buffers.create(6,values.byteLength,100);await buffers.upload(vb,0,memory,4096,values.byteLength);
  new Uint16Array(memory,4096,4).set([0,1,2,0]);const ib=await buffers.create(7,6,101);await buffers.upload(ib,0,memory,4096,8);
  for(const index of [0,ib]){const payload=diagnosticDrawPacket(vertex,pixel,vb,index);new Uint8Array(memory,4096,payload.length).set(payload);await renderer.draw(decodeDraw(memory,4096,payload.length));const encoder=device.createCommandEncoder();encoder.copyTextureToBuffer({texture:color},{buffer:read,bytesPerRow:256},[32,32]);device.queue.submit([encoder.finish()]);await read.mapAsync(GPUMapMode.READ);const bytes=Array.from(new Uint8Array(read.getMappedRange(),16*256+16*4,4));read.unmap();if(bytes.join(',')!=='191,128,64,255')throw Error('draw packet output mismatch '+bytes);samples.push({indexed:!!index,rgba:[bytes[2],bytes[1],bytes[0],bytes[3]]});}
  const texturePixel=objects.create(1,new Uint8Array(await(await fetch('/generated/texture.bin')).arrayBuffer())),texture=await textures.create(1,1,1,21);
  new Uint8Array(memory,4096,4).set([233,121,17,255]);await textures.upload(texture,0,memory,4096,4,4);const texturedPayload=diagnosticDrawPacket(vertex,texturePixel,vb,ib,texture);new Uint8Array(memory,4096,texturedPayload.length).set(texturedPayload);await renderer.draw(decodeDraw(memory,4096,texturedPayload.length));
  const texEncoder=device.createCommandEncoder();texEncoder.copyTextureToBuffer({texture:color},{buffer:read,bytesPerRow:256},[32,32]);device.queue.submit([texEncoder.finish()]);await read.mapAsync(GPUMapMode.READ);const texBytes=Array.from(new Uint8Array(read.getMappedRange(),16*256+16*4,4));read.unmap();if(texBytes.join(',')!=='233,121,17,255')throw Error('textured packet output mismatch '+texBytes);samples.push({indexed:true,textured:true,rgba:[17,121,233,255]});
  const sparseBytes=new Uint8Array(await(await fetch('/generated/texture.bin')).arrayBuffer()),sparseWords=new Uint32Array(sparseBytes.buffer);sparseWords[6]|=7;sparseWords[10]|=7;
  const sparsePixel=objects.create(1,sparseBytes),reflection=objects.pair(vertex,sparsePixel).pixel.samplers;if(reflection.length!==1||reflection[0].textureBinding!==7||reflection[0].samplerBinding!==0)throw Error('sparse sampler reflection mismatch');
  const sparsePayload=diagnosticDrawPacket(vertex,sparsePixel,vb,ib,texture,7);new Uint8Array(memory,4096,sparsePayload.length).set(sparsePayload);await renderer.draw(decodeDraw(memory,4096,sparsePayload.length));const sparseEncoder=device.createCommandEncoder();sparseEncoder.copyTextureToBuffer({texture:color},{buffer:read,bytesPerRow:256},[32,32]);device.queue.submit([sparseEncoder.finish()]);await read.mapAsync(GPUMapMode.READ);const sparseResult=Array.from(new Uint8Array(read.getMappedRange(),16*256+16*4,4));read.unmap();if(sparseResult.join(',')!=='233,121,17,255')throw Error('sparse texture binding mismatch');samples.push({samplerSlot:7,rgba:[17,121,233,255]});
  textures.destroy(texture);let staleTextureRejected=false;try{await renderer.draw(decodeDraw(memory,4096,sparsePayload.length))}catch(e){staleTextureRejected=e instanceof RangeError}if(!staleTextureRejected)throw Error('released texture accepted by draw');
  const payload=diagnosticDrawPacket(vertex,pixel,vb);new Uint8Array(memory,4096,payload.length).set(payload);const packet=decodeDraw(memory,4096,payload.length);packet.max=100;let rejected=false;try{await renderer.draw(packet)}catch(e){rejected=e instanceof RangeError}if(!rejected)throw Error('out-of-bounds draw accepted');
  rejected=false;try{decodeDraw(memory,4096,payload.length-4)}catch{rejected=true}if(!rejected)throw Error('truncated draw packet accepted');
  const viewportPayload=diagnosticDrawPacket(vertex,pixel,vb);new Uint8Array(memory,4096,viewportPayload.length).set(viewportPayload);const viewportPacket=decodeDraw(memory,4096,viewportPayload.length);viewportPacket.state.set(RS.ZENABLE,1);viewportPacket.viewport.set([4,8,16,16,0x3f400000,0x3f800000]);
  const clearEncoder=device.createCommandEncoder(),clearPass=clearEncoder.beginRenderPass({colorAttachments:[{view:color.createView(),loadOp:'clear',storeOp:'store',clearValue:[0,0,0,1]}],depthStencilAttachment:{view:depth.createView(),depthLoadOp:'clear',depthStoreOp:'store',depthClearValue:.75,stencilLoadOp:'clear',stencilStoreOp:'store',stencilClearValue:0}});clearPass.end();device.queue.submit([clearEncoder.finish()]);
  async function viewportSamples(){const encoder=device.createCommandEncoder();encoder.copyTextureToBuffer({texture:color},{buffer:read,bytesPerRow:256},[32,32]);device.queue.submit([encoder.finish()]);await read.mapAsync(GPUMapMode.READ);const mapped=read.getMappedRange();const results=[12,24].map(x=>Array.from(new Uint8Array(mapped,16*256+x*4,4)));read.unmap();return results;}
  await renderer.draw(viewportPacket);const rejectedDepth=await viewportSamples();if(rejectedDepth[0].join(',')!=='0,0,0,255')throw Error('viewport depth range was ignored');
  const compiled=renderer.cache.compilations;viewportPacket.viewport[4]=0;await renderer.draw(viewportPacket);const viewportPixels=await viewportSamples();if(viewportPixels[0].join(',')!=='191,128,64,255'||viewportPixels[1].join(',')!=='0,0,0,255'||renderer.cache.compilations!==compiled)throw Error('viewport bounds or dynamic pipeline reuse failed');
  viewportPacket.viewport[2]=33;let viewportRejected=false;try{await renderer.draw(viewportPacket)}catch(e){viewportRejected=e instanceof RangeError}if(!viewportRejected)throw Error('oversized viewport accepted');samples.push({viewport:[4,8,16,16],depthRangeRejected:rejectedDepth,insideOutsideBGRA:viewportPixels});
  return{result:'passed',samples,draws:6,checks:['viewport rectangle and depth range verified by GPU pixels','viewport changes reuse pipeline','reflected sampler slots 0 and 7 produce expected textured pixels','released texture draw rejected','decoded draw packets reach GPU rendering','indexed and nonindexed output matched','buffer overflow and truncated packets rejected'],HumusFrames:0};
 }finally{renderer.dispose();textures.dispose();objects.dispose();buffers.dispose();color.destroy();depth.destroy();read.destroy();const error=await device.popErrorScope();if(error)throw Error(error.message)}
}
