import {TextureStorage} from './gpu-textures.js';
export async function testTextures(device){
 const storage=new TextureStorage(device),memory=new SharedArrayBuffer(16384),bytes=new Uint8Array(memory);
 const assert=(v,m)=>{if(!v)throw Error(m)};
 const rejects=async fn=>{try{await fn()}catch(e){if(e instanceof RangeError)return;throw e}throw Error('invalid texture operation accepted')};
 async function read(id,level,layer=0){const t=storage.get(id),m=t.mips?.[level]??{rows:t.height,rowBytes:t.width*4,physicalWidth:t.width,physicalHeight:t.height},staging=device.createBuffer({size:256*m.rows,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});try{const enc=device.createCommandEncoder();enc.copyTextureToBuffer({texture:t.texture,mipLevel:level,origin:{x:0,y:0,z:layer}},{buffer:staging,bytesPerRow:256,rowsPerImage:m.rows},[m.physicalWidth,m.physicalHeight,1]);device.queue.submit([enc.finish()]);await staging.mapAsync(GPUMapMode.READ);const result=[],view=new Uint8Array(staging.getMappedRange());for(let row=0;row<m.rows;row++)result.push(...view.slice(row*256,row*256+m.rowBytes*(t.format===50?4:1)));return result}finally{staging.destroy()}}
 async function sampleCube(id){
  const t=storage.get(id),output=device.createBuffer({size:96,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC}),staging=device.createBuffer({size:96,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});
  const code='@group(0) @binding(0) var image:texture_cube<f32>; @group(0) @binding(1) var imageSampler:sampler; @group(0) @binding(2) var<storage,read_write> colors:array<vec4<f32>,6>; @compute @workgroup_size(1) fn main(@builtin(global_invocation_id) id:vec3<u32>){let directions=array<vec3<f32>,6>(vec3<f32>(1,0,0),vec3<f32>(-1,0,0),vec3<f32>(0,1,0),vec3<f32>(0,-1,0),vec3<f32>(0,0,1),vec3<f32>(0,0,-1));colors[id.x]=textureSampleLevel(image,imageSampler,directions[id.x],0.0);}';
  try{const pipeline=await device.createComputePipelineAsync({layout:'auto',compute:{module:device.createShaderModule({code}),entryPoint:'main'}}),group=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:t.view},{binding:1,resource:device.createSampler({minFilter:'nearest',magFilter:'nearest'})},{binding:2,resource:{buffer:output}}]}),enc=device.createCommandEncoder(),pass=enc.beginComputePass();pass.setPipeline(pipeline);pass.setBindGroup(0,group);pass.dispatchWorkgroups(6);pass.end();enc.copyBufferToBuffer(output,0,staging,0,96);device.queue.submit([enc.finish()]);await staging.mapAsync(GPUMapMode.READ);return Array.from(new Float32Array(staging.getMappedRange())).map(value=>Math.round(value*255));}finally{output.destroy();staging.destroy()}
 }
 try{
  const rgba=await storage.create(2,2,0,21),opaque=await storage.create(2,2,1,22);
  bytes.set([3,2,1,4,7,6,5,8,99,99,99,99,11,10,9,12,15,14,13,16],4096);
  await storage.upload(rgba,0,memory,4096,12,20);await storage.upload(opaque,0,memory,4096,12,20);
  assert((await read(rgba,0)).join(',')==='3,2,1,4,7,6,5,8,11,10,9,12,15,14,13,16','pitched BGRA upload mismatch');
  assert((await read(opaque,0)).join(',')==='3,2,1,255,7,6,5,255,11,10,9,255,15,14,13,255','XRGB alpha mismatch');assert(bytes[4099]===4,'XRGB conversion mutated guest');
  const lum=await storage.create(2,2,0,50);bytes.set([0,64,99,128,255],4096);await storage.upload(lum,0,memory,4096,3,5);
  assert((await read(lum,0)).join(',')==='0,0,0,255,64,64,64,255,128,128,128,255,255,255,255,255','L8 luminance replication mismatch');assert(bytes[4098]===99,'L8 upload mutated guest');assert(storage.get(lum).bytes===20,'L8 expanded GPU accounting');
  bytes[4096]=23;await storage.upload(lum,1,memory,4096,1,1);assert((await read(lum,1)).join(',')==='23,23,23,255','L8 tail mip');
  const compressed=[];
  if(device.features.has('texture-compression-bc'))for(const format of [0x31545844,0x33545844,0x35545844]){
   const id=await storage.create(8,8,0,format),t=storage.get(id);
   for(let level=0;level<t.levels;level++){const m=t.mips[level],length=m.rows*m.rowBytes;for(let i=0;i<length;i++)bytes[4096+i]=(i+level*17)&255;const expected=Array.from(bytes.slice(4096,4096+length));await storage.upload(id,level,memory,4096,m.rowBytes,length);assert((await read(id,level)).join(',')===expected.join(','),'compressed mip upload mismatch');}
   compressed.push({format,levels:t.levels,smallestMip:[1,1]});
  }
  const cube=await storage.create(2,2,1,21,6),faceBytes=[[0,0,255,255],[0,255,0,255],[255,0,0,255],[0,255,255,255],[255,0,255,255],[255,255,0,255]];
  for(let face=0;face<6;face++){bytes.fill(0,4096,4112);for(let pixel=0;pixel<4;pixel++)bytes.set(faceBytes[face],4096+pixel*4);await storage.upload(cube,0,memory,4096,8,16,face);assert((await read(cube,0,face)).join(',')===Array(4).fill(faceBytes[face]).flat().join(','),'cube face upload mismatch '+face);}
  const sampled=await sampleCube(cube),expected=[[255,0,0,255],[0,255,0,255],[0,0,255,255],[255,255,0,255],[255,0,255,255],[0,255,255,255]].flat();assert(sampled.join(',')===expected.join(','),'cube face sampling/orientation mismatch');
  const renderTexture=await storage.create(2,2,1,21,1,1),renderTarget=storage.attachment(renderTexture,0,0,1),renderCube=await storage.create(2,2,1,21,6,1),cubeTarget=storage.attachment(renderCube,3,0,1),depthSurface=await storage.createSurface(2,2,75,2),depthTarget=storage.attachment(depthSurface,0,0,2),standaloneColor=await storage.createSurface(2,2,22,1),standaloneTarget=storage.attachment(standaloneColor,0,0,1);
  const renderEncoder=device.createCommandEncoder(),renderPass=renderEncoder.beginRenderPass({colorAttachments:[{view:renderTarget.view,loadOp:'clear',storeOp:'store',clearValue:[17/255,121/255,233/255,1]}],depthStencilAttachment:{view:depthTarget.view,depthLoadOp:'clear',depthStoreOp:'store',depthClearValue:1,stencilLoadOp:'clear',stencilStoreOp:'store',stencilClearValue:3}});renderPass.end();const cubePass=renderEncoder.beginRenderPass({colorAttachments:[{view:cubeTarget.view,loadOp:'clear',storeOp:'store',clearValue:[0,1,0,1]}]});cubePass.end();const standalonePass=renderEncoder.beginRenderPass({colorAttachments:[{view:standaloneTarget.view,loadOp:'clear',storeOp:'store',clearValue:[1,0,0,1]}]});standalonePass.end();device.queue.submit([renderEncoder.finish()]);
  assert((await read(renderTexture,0)).join(',')==='233,121,17,255,233,121,17,255,233,121,17,255,233,121,17,255','render-target texture clear/readback mismatch');assert((await read(renderCube,0,3)).join(',')==='0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255','cube render-target face mismatch');assert((await read(standaloneColor,0)).join(',')==='0,0,255,255,0,0,255,255,0,0,255,255,0,0,255,255','standalone render-target clear/readback mismatch');assert(depthTarget.stencil,'D24S8 attachment lost stencil capability');
  await rejects(()=>storage.upload(rgba,2,memory,4096,8,16));await rejects(()=>storage.upload(rgba,0,memory,4096,4,16));await rejects(()=>storage.upload(rgba,0,memory,16380,8,16));await rejects(()=>storage.upload(rgba,0,memory,4096,12,19));await rejects(()=>storage.upload(cube,0,memory,4096,8,16,6));await rejects(()=>storage.create(3,4,1,0x31545844));await rejects(()=>storage.create(2,3,1,21,6));
  storage.destroy(rgba);await rejects(()=>storage.upload(rgba,0,memory,4096,8,16));storage.dispose();assert(storage.bytes===0,'texture budget leaked');
  return {result:'passed',compressed,checks:['2D and cube render-target textures plus standalone color/depth surfaces clear through hardware WebGPU','2D/cube render-target subresources and standalone color surface read back expected pixels','L8 luminance replication, opaque alpha, pitch and tail mip verified','GPU readback verifies pitched BGRA rows','XRGB samples opaque without modifying guest','compressed mip payloads including 2x2 and 1x1 copied exactly','six D3D cube faces upload, orient, and sample through a cube view','invalid ranges, cube layers, descriptions, and stale handles rejected','resource budget released'],HumusFrames:0};
 }finally{storage.dispose()}
}
